[global]
server.port = 8501
server.address = "0.0.0.0"
client.toolbarMode = "minimal"

[logger]
level = "info"

[runner]
magicEnabled = true

[browser]
gatherUsageStats = false

[server]
headless = true

[client]
showErrorDetails = true

